//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaTea.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.PaymentInfoes = new HashSet<PaymentInfo>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderStatus { get; set; }
        public string InvoiceNumber { get; set; }
        public int CustomerBillingAddressId { get; set; }
        public int CustomerShippingAddressId { get; set; }
        public string OrderNumber { get; set; }
    
        public virtual CustomerAddress CustomerBillingAddress { get; set; }
        public virtual CustomerAddress CustomerShippingAddress { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<PaymentInfo> PaymentInfoes { get; set; }
    }
}
