//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaTea.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInfo
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string Name { get; set; }
        public string CreditCardNumber { get; set; }
        public string ExpiredDate { get; set; }
        public string SecurityCode { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
