//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaTea.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public string CatalogNumber { get; set; }
        public string ProductName { get; set; }
        public int ProductCategoryId { get; set; }
        public decimal ProductPackageSize { get; set; }
        public decimal ProductUnitPrice { get; set; }
        public string ProductDescription { get; set; }
        public decimal Stock { get; set; }
        public string PicPathThumbnail { get; set; }
        public string PicPathDeatil { get; set; }
        public string ProductChineseName { get; set; }
        public string PackageUnit { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
